[package]
name = "np-feeds"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
np-store = { path = "../np-store" }
async-trait = { workspace = true }
chrono = { workspace = true }
feed-rs = "3.0.0"
futures = { workspace = true }
reqwest = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
unicode-normalization = "0.1.25"
url = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
wiremock = "0.6.5"
