import { invoke } from '@tauri-apps/api/core';
import type {
  AdblockStatus, BlockedCounts, DeleteScope, HistoryEntry, HistoryFilter, NetMode, PrivacyStatus, Rect, RefreshReport,
  SearchSource, Suggestion, TabId, TabInfo, TabsSnapshot, TabView,
} from './types';
import type {
  BeginResult, CaptureInput, CaptureText, CdxRow, CoverageResult, CustomOutlet, Edition, EventCard, EventDetail, IngestReport,
  LexiconScore, OfflineArticle, OfflineHit, OfflineSettings, OutletLean, SavedArticle, TextDiff, TopicState, Watch, WaybackHistory,
} from './types';

/** Único punto de la UI que conoce los nombres de los comandos Rust. Los subproyectos añaden entradas. */
export const commands = {
  tabOpen: (args: { url?: string; private?: boolean; activate?: boolean; openerId?: TabId } = {}) => invoke<TabInfo>('tab_open', args),
  tabClose: (tabId: TabId) => invoke<void>('tab_close', { tabId }),
  tabActivate: (tabId: TabId) => invoke<void>('tab_activate', { tabId }),
  tabNavigate: (tabId: TabId, input: string) => invoke<void>('tab_navigate', { tabId, input }),
  tabBack: (tabId: TabId) => invoke<void>('tab_back', { tabId }),
  tabForward: (tabId: TabId) => invoke<void>('tab_forward', { tabId }),
  tabReload: (tabId: TabId) => invoke<void>('tab_reload', { tabId }),
  tabSetView: (tabId: TabId, view: TabView) => invoke<void>('tab_set_view', { tabId, view }),
  tabSetBounds: (rect: Rect) => invoke<void>('tab_set_bounds', { rect }),
  tabPin: (tabId: TabId, pinned: boolean) => invoke<void>('tab_pin', { tabId, pinned }),
  tabGroup: (tabIds: TabId[], opts: { name?: string; groupId?: number } = {}) => invoke<number | null>('tab_group', { tabIds, name: opts.name, groupId: opts.groupId }),
  tabUngroup: (tabId: TabId) => invoke<void>('tab_ungroup', { tabId }),
  tabGroupUpdate: (groupId: number, u: { name?: string; color?: string; collapsed?: boolean }) =>
    invoke<void>('tab_group_update', { groupId, name: u.name, color: u.color, collapsed: u.collapsed }),
  tabCloseGroup: (groupId: number) => invoke<void>('tab_close_group', { groupId }),
  tabsSnapshot: () => invoke<TabsSnapshot>('tabs_snapshot'),
  resourcesSnooze: (minutes?: number) => invoke<void>('resources_snooze', { minutes }),
  resourcesCloseBackground: () => invoke<number>('resources_close_background'),
  appExit: () => invoke<void>('app_exit'),
  overlayOpen: (tabId: TabId) => invoke<string | null>('overlay_open', { tabId }),
  ctxClose: (tabId: TabId) => invoke<void>('ctx_close', { tabId }),
  ctxEdit: (tabId: TabId, action: 'delete' | 'paste' | 'selectAll', text?: string) => invoke<void>('ctx_edit', { tabId, action, text }),
  clipboardText: () => invoke<string | null>('clipboard_text'),
  chromeSetMotion: (reduced: boolean) => invoke<void>('chrome_set_motion', { reduced }),
  chromeSetTheme: (theme: 'paper' | 'ink') => invoke<void>('chrome_set_theme', { theme }),

  settingsGet: <T = unknown>(key: string) => invoke<T | null>('settings_get', { key }),
  settingsSet: (key: string, value: unknown) => invoke<void>('settings_set', { key, value }),
  settingsList: (prefix: string) => invoke<[string, unknown][]>('settings_list', { prefix }),

  historyRecordVisit: (tabId: TabId, url: string, title: string) => invoke<string | null>('history_record_visit', { tabId, url, title }),
  historyRecordSearch: (query: string, source: SearchSource) => invoke<string | null>('history_record_search', { query, source }),
  historyMarkAnalyzed: (url: string) => invoke<number>('history_mark_analyzed', { url }),
  historySearch: (filter: HistoryFilter) => invoke<HistoryEntry[]>('history_search', { filter }),
  historyDelete: (scope: DeleteScope) => invoke<number>('history_delete', { scope }),
  omniboxSuggest: (input: string) => invoke<Suggestion[]>('omnibox_suggest', { input }),

  secretSet: (key: string, value: string) => invoke<void>('secret_set', { key, value }),
  secretHas: (key: string) => invoke<boolean>('secret_has', { key }),
  secretDelete: (key: string) => invoke<void>('secret_delete', { key }),

  configRead: (name: string) => invoke<string>('config_read', { name }),

  privacyStatus: () => invoke<PrivacyStatus>('privacy_status'),
  netSetMode: (mode: NetMode) => invoke<PrivacyStatus>('net_set_mode', { mode }),
  torSetExitCountry: (country: string | null) => invoke<PrivacyStatus>('tor_set_exit_country', { country }),
  torNewCircuit: (tabId?: TabId) => invoke<PrivacyStatus>('tor_new_circuit', { tabId }),
  privacySetRouting: (r: { aiViaTor?: boolean; feedsViaTor?: boolean }) => invoke<PrivacyStatus>('privacy_set_routing', r),
  tabWithoutTor: (tabId: TabId) => invoke<PrivacyStatus>('tab_without_tor', { tabId }),
  adblockStatus: () => invoke<AdblockStatus>('adblock_status'),
  adblockSetEnabled: (enabled: boolean) => invoke<AdblockStatus>('adblock_set_enabled', { enabled }),
  adblockSetList: (id: string, enabled: boolean) => invoke<AdblockStatus>('adblock_set_list', { id, enabled }),
  adblockRefresh: () => invoke<RefreshReport>('adblock_refresh'),
  blockedCounts: (tabId?: TabId) => invoke<BlockedCounts>('blocked_counts', { tabId }),
  feedsRefreshNow: () => invoke<IngestReport>('feeds_refresh_now'),
  coverageFor: (url: string, title: string, excerpt?: string) => invoke<CoverageResult>('coverage_for', { url, title, excerpt }),
  eventsBriefing: (limit?: number) => invoke<EventCard[]>('events_briefing', { limit }),
  eventsSearch: (query: string) => invoke<EventCard[]>('events_search', { query }),
  eventDetail: (eventId: number) => invoke<EventDetail | null>('event_detail', { eventId }),
  outletsList: () => invoke<OutletLean[]>('outlets_list'),
  outletOverrideSet: (outletId: string, lean: number | null, note?: string) => invoke<OutletLean[]>('outlet_override_set', { outletId, lean, note }),
  outletStatsRecompute: () => invoke<number>('outlet_stats_recompute'),
  customOutletsList: () => invoke<CustomOutlet[]>('custom_outlets_list'),
  customOutletAdd: (outlet: CustomOutlet) => invoke<CustomOutlet[]>('custom_outlet_add', { outlet }),
  customOutletRemove: (domain: string) => invoke<CustomOutlet[]>('custom_outlet_remove', { domain }),
  topicsList: () => invoke<TopicState[]>('topics_list'),
  topicSetFollowing: (topicId: string, following: boolean) => invoke<TopicState[]>('topic_set_following', { topicId, following }),
  watchAdd: (w: { articleUrl?: string; query?: string; eventId?: number }) => invoke<string>('watch_add', w),
  watchesList: () => invoke<Watch[]>('watches_list'),
  lexiconScore: (text: string, locale: string) => invoke<LexiconScore>('lexicon_score', { text, locale }),
  waybackCaptures: (url: string) => invoke<CdxRow[]>('wayback_captures', { url }),
  waybackCaptureHtml: (url: string, timestamp: string) => invoke<string>('wayback_capture_html', { url, timestamp }),
  waybackAnalyze: (url: string, captures: CaptureInput[]) => invoke<WaybackHistory>('wayback_analyze', { url, captures }),
  waybackDiff: (a: CaptureText, b: CaptureText) => invoke<TextDiff>('wayback_diff', { a, b }),
  savedAdd: (article: SavedArticle) => invoke<void>('saved_add', { article }),
  savedRemove: (url: string) => invoke<void>('saved_remove', { url }),
  savedList: () => invoke<SavedArticle[]>('saved_list'),
  savedGet: (url: string) => invoke<SavedArticle | null>('saved_get', { url }),
  offlineBegin: (date: string) => invoke<BeginResult>('offline_begin', { date }),
  offlineFetchHtml: (url: string) => invoke<string>('offline_fetch_html', { url }),
  offlineSaveImage: (editionId: string, name: string, dataBase64: string) => invoke<string>('offline_save_image', { editionId, name, dataBase64 }),
  offlineAddArticle: (a: { editionId: string; url: string; title: string; outlet: string | null; articleJson: string; analysisJson: string | null }) =>
    invoke<void>('offline_add_article', a),
  offlineFinish: (editionId: string, summaryJson: string, date: string) => invoke<string[]>('offline_finish', { editionId, summaryJson, date }),
  offlineEditions: () => invoke<Edition[]>('offline_editions'),
  offlineEdition: (id: string) => invoke<OfflineArticle[]>('offline_edition', { id }),
  offlineSearch: (query: string) => invoke<OfflineHit[]>('offline_search', { query }),
  offlineCleanup: () => invoke<string[]>('offline_cleanup'),
};
